services:
  db:
    image: rasulkireev/custom-postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  backend:
    image: ghcr.io/rasulkireev/marketing-agents:latest
    working_dir: /app
    command: sh -c "python manage.py migrate && gunicorn seo_blog_bot.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      frontend:
        condition: service_started
    env_file:
      - .env

  workers:
    image: ghcr.io/rasulkireev/marketing-agents-workers:latest
    working_dir: /app
    command: python manage.py qcluster
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
