services:
  - type: web
    name: marketingagents-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt &&
      npm ci &&
      npm run build &&
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      python manage.py qcluster &
      gunicorn seo_blog_bot.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
    plan: free
    healthCheckPath: /

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: ENVIRONMENT
        value: prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketingagents-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: marketingagents-redis
          property: connectionString

      # Auto-configure hosts
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"

      # Optional. If not specified, local FileSystemStorage is used for media files.
      - key: AWS_S3_ENDPOINT_URL
        value: ""
      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""

      # Basic email setup - can be configured later
      - key: MAILGUN_API_KEY
        value: ""

      # AI Keys
      - key: GEMINI_API_KEY
        value: ""
      - key: PERPLEXITY_API_KEY
        value: ""
      - key: JINA_READER_API_KEY
        value: ""
      - key: KEYWORDS_EVERYWHERE_API_KEY
        value: ""

  - type: redis
    name: marketingagents-redis
    plan: free
    ipAllowList: [] # only allow internal connections
    maxmemoryPolicy: allkeys-lfu

databases:
  - name: marketingagents-db
    databaseName: marketingagents
    user: marketingagents_user
    plan: free
