# Generated by Django 5.2.6 on 2025-10-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_keyword_got_people_also_search_for_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='content_too_short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='placeholders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='valid_ending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generatedblogpost',
            name='icon',
            field=models.ImageField(blank=True, upload_to='generated_blog_post_icons/'),
        ),
        migrations.AlterField(
            model_name='generatedblogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='generated_blog_post_images/'),
        ),
    ]
