# Generated by Django 5.2.6 on 2025-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_generatedblogpost_content_too_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedblogpost',
            name='valid_ending',
            field=models.BooleanField(default=True),
        ),
    ]
