# Generated by Django 5.2.7 on 2025-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_generatedblogpost_content_too_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='starts_with_header',
            field=models.BooleanField(default=False),
        ),
    ]
