# Generated by Django 5.2.7 on 2025-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_starts_with_header_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sitemap_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('SITEMAP', 'Sitemap')], default='AI', help_text='Source of the page: AI-discovered or from Sitemap', max_length=20),
        ),
    ]
