# Generated by Django 5.2.6 on 2025-10-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_starts_with_header_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='lists_without_empty_line_above',
            field=models.BooleanField(default=False),
        ),
    ]
