# Generated by Django 5.2.6 on 2025-10-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_generatedblogpost_valid_ending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedblogpost',
            old_name='valid_ending',
            new_name='has_valid_ending',
        ),
    ]
