# Generated by Django on 2025-10-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_starts_with_header_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sitemap_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="SitemapPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("date_scraped", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("markdown_content", models.TextField(blank=True, default="")),
                ("date_analyzed", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitemap_pages",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "url")},
            },
        ),
    ]
