# Generated by Django 5.2.7 on 2025-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_project_sitemap_url_projectpage_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectpage',
            unique_together={('project', 'url')},
        ),
        migrations.AddField(
            model_name='projectpage',
            name='always_use',
            field=models.BooleanField(default=False, help_text='When enabled, this page link will always be included in generated blog posts'),
        ),
    ]
