# Generated by Django 5.2.7 on 2025-11-02 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_projectpage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferrerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.CharField(help_text="The referrer code from URL parameter (e.g., 'producthunt' from ?ref=producthunt)", max_length=100, unique=True)),
                ('referrer_printable_name', models.CharField(help_text="Human-readable name to display in banner (e.g., 'Product Hunt')", max_length=200)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='When to stop showing this banner', null=True)),
                ('coupon_code', models.CharField(blank=True, help_text='Optional discount coupon code', max_length=100)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount from 0.00 (0%) to 1.00 (100%)', max_digits=3)),
                ('is_active', models.BooleanField(default=True, help_text='Manually enable/disable banner without deleting it')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
