# Generated by Django 5.2.7 on 2025-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_referrerbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerbanner',
            name='background_color',
            field=models.CharField(default='bg-gradient-to-r from-red-500 to-red-600', help_text="Tailwind CSS background color classes (e.g., 'bg-gradient-to-r from-red-500 to-red-600' or 'bg-blue-600')", max_length=100),
        ),
        migrations.AddField(
            model_name='referrerbanner',
            name='text_color',
            field=models.CharField(default='text-white', help_text="Tailwind CSS text color class (e.g., 'text-white' or 'text-gray-900')", max_length=50),
        ),
    ]
