# Generated by Django 5.2.7 on 2025-11-02 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_referrerbanner_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(help_text='The recipient email address', max_length=254)),
                ('email_type', models.CharField(choices=[('EMAIL_CONFIRMATION', 'Email Confirmation'), ('WELCOME', 'Welcome'), ('FEEDBACK_NOTIFICATION', 'Feedback Notification')], help_text='Type of email sent', max_length=50)),
                ('profile', models.ForeignKey(blank=True, help_text='Associated user profile, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to='core.profile')),
            ],
            options={
                'verbose_name': 'Email Sent',
                'verbose_name_plural': 'Emails Sent',
                'ordering': ['-created_at'],
            },
        ),
    ]
