# Generated by Django 5.2.7 on 2025-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_emailsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='blog_post',
            field=models.TextField(blank=True, default=''),
        ),
    ]
