# Generated by Django 5.2.7 on 2025-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_competitor_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_automatic_og_image_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image_style',
            field=models.CharField(blank=True, choices=[('Modern Gradient', 'Modern Gradient'), ('Minimalist Clean', 'Minimalist Clean'), ('Bold Typography', 'Bold Typography'), ('Tech Abstract', 'Tech Abstract'), ('Professional Corporate', 'Professional Corporate'), ('Creative Artistic', 'Creative Artistic'), ('Dark Mode', 'Dark Mode'), ('Vibrant Colorful', 'Vibrant Colorful')], default='Modern Gradient', max_length=50),
        ),
    ]
