# Generated by Django 5.2.7 on 2025-11-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_project_enable_automatic_og_image_generation_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS pg_stat_statements;',
            reverse_sql='DROP EXTENSION IF EXISTS pg_stat_statements;',
        ),
    ]
