# Generated by Django 5.2.7 on 2025-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_og_image_generation_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enable_automatic_og_image_generation',
            field=models.BooleanField(default=True),
        ),
    ]
