# Generated by Django 5.2.7 on 2025-11-07 11:23

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20251107_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, default=None, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, default=None, dimensions=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='competitor_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='projectpage',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='projectpage_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
