# Generated by Django 5.2.7 on 2025-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_competitor_embedding_projectpage_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='generation_structure',
            field=models.TextField(blank=True, default='', help_text='Stores the outline/structure from the first pipeline step'),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='pipeline_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores timestamps, AI model info, and token usage per step'),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='pipeline_state',
            field=models.JSONField(blank=True, default=None, help_text='Tracks the current step and status of the generation pipeline', null=True),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='raw_content',
            field=models.TextField(blank=True, default='', help_text='Stores content before internal links are added'),
        ),
    ]
