# Generated by Django 5.2.8 on 2025-11-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_autosubmissionsetting_deleted_at_blogpost_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='content_too_short',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='has_valid_ending',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='placeholders',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='starts_with_header',
        ),
    ]
