# Generated by Django 5.2.7 on 2025-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_generatedblogpost_generation_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='content_too_short',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='has_valid_ending',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='placeholders',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='starts_with_header',
        ),
        migrations.AlterField(
            model_name='blogposttitlesuggestion',
            name='content_type',
            field=models.CharField(choices=[('SEO', 'SEO')], default='SEO', max_length=20),
        ),
    ]
