# Generated by Django 5.2.7 on 2025-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_autosubmissionsetting_deleted_at_blogpost_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='content_too_short',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='has_valid_ending',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='placeholders',
        ),
        migrations.RemoveField(
            model_name='generatedblogpost',
            name='starts_with_header',
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='is_content_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='validation_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='validation_issues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
