# Generated by Django 5.2.8 on 2025-11-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_generatedblogpost_content_too_short_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedblogpost',
            old_name='title',
            new_name='title_suggestion',
        ),
    ]
