# Generated by Django 5.2.8 on 2025-11-20 12:54

from django.db import migrations, models


def populate_title_from_title_suggestion(apps, schema_editor):
    """
    Forward migration: Populate title field from title_suggestion.title
    """
    GeneratedBlogPost = apps.get_model("core", "GeneratedBlogPost")
    BlogPostTitleSuggestion = apps.get_model("core", "BlogPostTitleSuggestion")

    for blog_post in GeneratedBlogPost.objects.select_related("title_suggestion").all():
        if blog_post.title_suggestion:
            blog_post.title = blog_post.title_suggestion.title
            blog_post.save(update_fields=["title"])


def reverse_populate_title(apps, schema_editor):
    """
    Reverse migration: Clear title field (since it will be removed)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_title_generatedblogpost_title_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='title',
            field=models.CharField(max_length=250, null=True, blank=True),
        ),
        migrations.RunPython(
            populate_title_from_title_suggestion,
            reverse_code=reverse_populate_title,
        ),
        migrations.AlterField(
            model_name='generatedblogpost',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
