# Generated by Django 5.2.8 on 2025-11-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_generatedblogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='particiate_in_link_exchange',
            field=models.BooleanField(default=False),
        ),
    ]
