# Generated by Django 5.2.8 on 2025-11-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_project_particiate_in_link_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enable_automatic_og_image_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='enable_automatic_post_generation',
            field=models.BooleanField(default=False),
        ),
    ]
