# Generated by Django 5.2.8 on 2025-11-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_project_enable_automatic_og_image_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='email_type',
            field=models.CharField(choices=[('EMAIL_CONFIRMATION', 'Email Confirmation'), ('WELCOME', 'Welcome'), ('FEEDBACK_NOTIFICATION', 'Feedback Notification'), ('BLOG_POST_READY', 'Blog Post Ready')], help_text='Type of email sent', max_length=50),
        ),
    ]
