# Generated by Django 5.2.8 on 2025-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_emailsent_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='email_type',
            field=models.CharField(choices=[('EMAIL_CONFIRMATION', 'Email Confirmation'), ('WELCOME', 'Welcome'), ('FEEDBACK_NOTIFICATION', 'Feedback Notification'), ('BLOG_POST_READY', 'Blog Post Ready'), ('FEEDBACK_REQUEST', 'Feedback Request')], help_text='Type of email sent', max_length=50),
        ),
    ]
