# Generated by Django 5.2.8 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_emailsent_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("profile", "url")},
        ),
    ]
