# Generated by Django 5.2.9 on 2025-12-27 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_backlink_generatedblogpostresearchquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedblogpostresearchlink',
            old_name='markdown_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='generatedblogpostresearchlink',
            old_name='summary',
            new_name='general_summary',
        ),
        migrations.RemoveField(
            model_name='generatedblogpostresearchlink',
            name='question',
        ),
        migrations.AddField(
            model_name='generatedblogpostresearchlink',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedblogpostresearchlink',
            name='summary_for_question_research',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='generatedblogpostresearchlink',
            name='date_scraped',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
