PLACEHOLDER_PATTERNS = [
    "insert image here",
    "insert image",
    "add image here",
    "add image",
    "image placeholder",
    "placeholder image",
    "[image]",
    "[insert image]",
    "example 1",
    "example 2",
    "example 3",
    "example here",
    "add example",
    "insert example",
    "[example]",
    "todo:",
    "to do:",
    "tbd",
    "to be determined",
    "coming soon",
    "under construction",
    "placeholder text",
    "lorem ipsum",
    "sample text",
    "dummy text",
    "[placeholder]",
    "[todo]",
    "[tbd]",
    "fill in",
    "replace this",
    "update this",
    "change this",
    "modify this",
    "edit this",
    "xxx",
    "yyy",
    "zzz",
    "Image Suggestion",
    "Link Suggestion",
    "image suggestion",
    "link suggestion",
]

PLACEHOLDER_BRACKET_PATTERNS = [
    r"\[.*?placeholder.*?\]",
    r"\[.*?insert.*?\]",
    r"\[.*?add.*?\]",
    r"\[.*?todo.*?\]",
    r"\[.*?tbd.*?\]",
    r"\[.*?example.*?\]",
]
